# Generated by Django 5.0.7 on 2024-07-15 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_transactions_wallet_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactions",
            old_name="wallet_id",
            new_name="user_id",
        ),
    ]
