# Generated by Django 5.0.7 on 2024-07-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_rename_wallet_id_transactions_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
