# Generated by Django 5.0.7 on 2024-07-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_transactions_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="invoice_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
