# Generated by Django 5.0.1 on 2024-08-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_transactions_transaction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="card_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="cvv",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="expiry_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="expiry_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
