# Generated by Django 5.0.1 on 2024-08-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_rename_user_id_transactions_userid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "PENDING"),
                    ("PROCESSING", "PROCESSING"),
                    ("COMPLETE", "COMPLETE"),
                    ("FAILED", "FAILED"),
                    ("RETRY", "RETRY"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
