# Generated by Django 5.0.1 on 2024-08-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_alter_transactions_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
