# Generated by Django 5.0.1 on 2024-08-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0010_transactions_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="invoice_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
