# Generated by Django 5.0.1 on 2024-08-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0011_transactions_invoice_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MOBILE_MONEY", "MOBILE_MONEY"),
                    ("CARD_PAYMENT", "CARD_PAYMENT"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
