# Generated by Django 5.0.1 on 2024-08-14 00:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0013_alter_transactions_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("KES", "KES"), ("USD", "USD")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("M-PESA", "M-PESA"), ("CARD", "CARD")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MOBILE_MONEY", "MOBILE_MONEY"),
                            ("CARD_PAYMENT", "CARD_PAYMENT"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("COMPLETE", "COMPLETE"),
                            ("FAILED", "FAILED"),
                            ("RETRY", "RETRY"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("phone_number", models.BigIntegerField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
                ("imageUrl", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "newBalance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reference",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("shopId", models.CharField(blank=True, max_length=100, null=True)),
                ("userId", models.CharField(blank=True, max_length=100, null=True)),
                ("walletId", models.CharField(blank=True, max_length=100, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                ("updatedAt", models.DateTimeField(auto_now_add=True, null=True)),
                ("invoice_id", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("orderId", models.CharField(blank=True, max_length=50, null=True)),
                ("customerId", models.CharField(blank=True, max_length=50, null=True)),
                ("statusType", models.CharField(blank=True, max_length=50, null=True)),
                ("items", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
