# Generated by Django 5.0.1 on 2024-08-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0014_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="items",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
